### ISSUE TITLE
Another Key Error: 'params' in FIle custom_components/sonoff/switch.py", line 22

### ISSUE THREAD

**Issue by TimDNN** [peterbuga/HASS-sonoff-ewelink#67] opened 2019-03-03 23:05 UTC
Hello, thanks for ur great job, but unfurtunaly i've got a dict Key Error while startinge the Home assistant.
I used ur debug Script, but everything seems to work good. I can see the offline and online devices with the debug Script.
Thanks for help in advance ;-)

2019-03-03 23:37:30 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform sonoff
Traceback (most recent call last):
  File "/home/tim/homeasi/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/tim/.homeassistant/custom_components/sonoff/switch.py", line 22, in async_setup_platform
    if 'switches' in device['params']:
KeyError: 'params'

**Comment by TimDNN** [comment] 2019-03-03 23:39
ok I got it working,
I had an Sonoff T1 which I was not be able to connect too my wifi.
Now I deleted it from my account and evreything works fine.

By the way I wondered where to see the Sonoff Devices.
--> U can see them at Overview/Switch/<your Device Names>.
Maybe it would be nice if u just could include an Screenshot on ur .md file so newes like me will see how the result should look like if everything is working correct ;-)

**Comment by peterbuga** [comment] 2019-03-04 11:50
> I had an Sonoff T1 which I was not be able to connect too my wifi.
> Now I deleted it from my account and evreything works fine.

this is an interesting possible bug, i'll try to look further into it but in theory when a device is offline it should not reach that line/error

regarding the screenshot, it's pretty basic that devices should show in the Dev section in HA, all the entities do! i'm definitely not going add screenshots to .md

**Comment by nzdazza** [comment] 2019-04-17 22:52
The sensor.py has a filter to check for the existence of the params dict, switch.py does not. I had the same issue and just put that same line of code and everything was good. Caused by partially setup device that had not checked in properly yet.

if 'params' not in device.keys(): continue # this should never happen... but just in case

**Comment by peterbuga** [comment] 2019-04-18 06:14
hi @nzdazza 
that's a valid fix (in a way ... because it *should never happen*) could you please post your output of `sonoff-debug.py` script? i'm interested to see what kind of device you have in the list that is missing the `params` key. 
by my understanding (so far) all the devices present this kind of key... but then again i might be wrong `¯\_(ツ)_/¯`

**Comment by nzdazza** [comment] 2019-04-18 08:07
It’s a partially setup sonoff 2 button wall switch. Of the 15 sonoffs I have these two 2 button devices will not complete the compatible mode setup. I’ll post the debug output shortly.

Regards,
Daryl Petersen.



On Thu, Apr 18, 2019 at 6:14 PM +1200, "Peter Buga" <notifications@github.com<mailto:notifications@github.com>> wrote:


hi @nzdazza<https://github.com/nzdazza>
that's a valid fix (in a way ... because it should never happen) could you please post your output of sonoff-debug.py script? i'm interested to see what kind of device you have in the list that is missing the params key.
by my understanding (so far) all the devices present this kind of key... but then again i might be wrong ¯\_(ツ)_/¯

**Closed** 2019-09-28 12:32 UTC
