### ISSUE TITLE
Is Sonoff Slampher supported?

### ISSUE THREAD

**Issue by oriziv** [peterbuga/HASS-sonoff-ewelink#79] opened 2019-04-01 08:49 UTC
Thank you for this project
I have sonoff slampher with firmware 1.7 and one with 3.0.0 are they supported as well?

Thanks

**Comment by peterbuga** [comment] 2019-04-01 08:55
@oriziv i have high confidence it should work. you'll most likely see it as a switch (because in the end that's what all they are) in HA but you can easily customize it to act as a light too.
please post the output from [sonoff-debug](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug) and i'll be able to give a more accurate detail

ps: i think someone else enquired about this device before and reported that it worked but my mind is a bit foggy about it 😅

**Comment by oriziv** [comment] 2019-04-01 09:35
It works! just validated on 1.7.0

**Comment by oriziv** [comment] 2019-04-01 09:35
Thank you!!

**Comment by oriziv** [comment] 2019-04-02 11:41
I will test it on the 3.0.0 as well and report, 
Thanks

**Comment by GuyKh** [comment] 2019-04-06 15:00
@oriziv - Supported.
I confirmed (also on 3.0.0).
Added it  to PR [86](https://github.com/peterbuga/HASS-sonoff-ewelink/pull/86)

**Comment by GuyKh** [comment] 2019-04-07 17:30
The PR was merged. I think this issue can be closed

**Comment by peterbuga** [comment] 2019-04-07 17:32
@GuyKh you Sir you are totally right 😅 👍 
i'm been so focused on refactoring some stuff that I totally forgot about it
thanks!

**Closed by peterbuga** 2019-04-07 17:32 UTC
