### ISSUE TITLE
Sonoffs turn from off to off occasionally.

### ISSUE THREAD

**Issue by krasatos** [peterbuga/HASS-sonoff-ewelink#93] opened 2019-04-16 10:53 UTC
Not an issue, more like an observation but thought i should mention it in case it is usefull or it means something more to you guys.

I have my sonoffs running my irrigation system so while testing (in order to be sure) i set up an automation that notifies me on any state change of my ewelink-connected sonoffs.
````
- id: 'XXXXXXX'
  alias: Notify Failsafe Irrigation 
  trigger:
  - entity_id: switch.XXXXXXX, switch.XXXXXXX, switch.XXXXXXX, switch.XXXXXXX, switch.XXXXXXX
    platform: state
  condition: []
  action:
  - data_template:
      message: "Switch {{ trigger.entity_id }} changed from {{ trigger.from_state.state}} to {{ trigger.to_state.state }} at {{ now().strftime('%H:%M')}}"
      title: Irrigation Alert
    service: notify.notify_html5

````

Throughout the day, (3-4 times daily i think) i get a set of notifications (one for every switch) that "switch XXX changed from off to off at xx:xx".

This does not affect me at all, i would guess it's a reconnection issue or a failsafe?
I just thought i should mention it, in case you guys missed it.
(feel free to close/delete my issue if this is not at all important)

Thanks again for this solution :)

**Comment by peterbuga** [comment] 2019-04-16 11:04
i really don't know what to say about this :| my component (as many similar ones) just write the state data **for HA to process**, without any (error) logs i really don't even know where to begin debugging this as i sort of believe it might be a HA bug *maaaaybe* caused by some fast-change states

**Comment by krasatos** [comment] 2019-04-16 11:06
It might even be some eWeLink refresh thing, IDK. I just thought i should inform you :)

**Comment by peterbuga** [comment] 2019-04-16 11:46
thanks for reporting it! for now i will close this issue cuz' i really don't know how i should treat it, but i will gladly re-open it if is actually the effect of a bigger problem.

as a small patch you could add another condition to trigger only when from-to state it's actually changed so it'll be on->off or off->on but never off->off (on->on). then again this should be decided (in theory at least) by HA not by you

**Closed by peterbuga** 2019-04-16 11:46 UTC
