### ISSUE TITLE
Integrations need to be in their own folder. Change switch/sonoff.py to sonoff/switch.py. This will stop working soon.

### ISSUE THREAD

**Issue by mrblur** [peterbuga/HASS-sonoff-ewelink#61] opened 2019-02-21 08:24 UTC
Home-Assistant (0.88) is changing custom components structure, would be nice to adjust and keep compatibility  :)

PS. Great job with this component!

**Comment by 2016for** [comment] 2019-02-22 10:54
Duplicate of #63 

Please look into [HA 0.88 breaking changes](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html) for Custom components.

So all sonoff custom component files have to be in config/custom_components/sonoff folder

So move /custom_components/sonoff.py to /custom_components/sonoff and rename to __init__.py
Rename /custom_components/sensor/sonoff.py to sensor.py and move to /custom_components/sonoff/

Similarly rename /custom_components/switch/sonoff.py to switch.py and move to /custom_components/sonoff/ 

So final file structure should be:

config/custom_components/sonoff/__init__.py (this was the main sonoff.py in custom_components folder)
config/custom_components/sonoff/sensor.py
config/custom_components/sonoff/sensor.py

**Comment by Tony763** [comment] 2019-02-22 20:52
**Peterbuga** already made a new branch with needed changes:
Check it here: [master-HA0.88+](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master-HA0.88+)

**Comment by springfall2008** [comment] 2019-03-15 12:37
This works for me too, perhaps merge it back to MAIN?

**Comment by alexhoffenreich** [comment] 2019-03-17 05:24
I had to change the init.py to __init__.pi and it started working

**Comment by alexhoffenreich** [comment] 2019-03-17 05:26
sorry... \_\_init\_\_.pi

**Comment by peterbuga** [comment] 2019-03-17 11:29
@alexhoffenreich `.pi`? could you please re-confirm this, it doesn't make any sense and you're just adding confusion. thanks

**Comment by alexhoffenreich** [comment] 2019-03-17 15:32
sorry... @2016for recommendation works. 
At first, I tried to rename the main sonoff.py file to init.py (as is seems to be written in his recommendation). Eventually i understood that is must be \_\_init\_\_.py, and the dunder (\_\_) before and after the "init" don't appear in the comment because \_\_ is transformed for bold text.
The .pi is of course a stupid typo. it should be .py

**Comment by aocana** [comment] 2019-03-18 16:10
please, could you updated the repository of this component with the new structure files/folder;

now folowing your notes we have have;

 custom_components
    ├── sonoff.py
    └── switch
        └── sonoff.py
    └── sensor
        └── sonoff.py

and need to be changed to : ????

**Comment by Tony763** [comment] 2019-03-18 18:00
You have it wrong. `init.py` MUST by` __init__.py`

`cp sonoff.py sonoff/__init__.py`

Correct way: Just get [master-HA0.88+](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master-HA0.88+)

**Comment by mclaudiopt** [comment] 2019-03-21 18:30
hi there. when i check configuration i get the following error:
Component not found: sonoff

![image](https://user-images.githubusercontent.com/48178294/54776165-700ea200-4c07-11e9-8460-cb0cfeef9857.png)

**Comment by Tony763** [comment] 2019-03-21 22:10
@mclaudiopt Which version oh Home assistant You are using? If it is version 0.88 and above, You have to rename files to correspond a new standard of HA plugins dictionary system.

This is from my installation of version 0.90:

![image](https://user-images.githubusercontent.com/5598750/54788022-e9b98680-4c2d-11e9-8b98-d57fd95abfaa.png)

You can rename files manualy or by @aocana 's way:
```
cd custom_components 
mkdir sonoff
cp sonoff.py sonoff/__init__.py
cp sensor/sonoff.py sonoff/sensor.py
cp switch/sonoff.py sonoff/switch.py
rm -rf switch/
rm -rf sensor/
rm -rf sonoff.py 
```

**Comment by lamboid** [comment] 2019-03-25 08:22
is the 0.88 version using the websockets code or the original? if not, can we just rename the websocket files as required???

**Comment by Tony763** [comment] 2019-03-25 21:04
I'm using normal version. For Websocket You can use [Websocket-HA0.88+](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/websocket-HA0.88+) branch.

**Closed** 2019-03-26 11:43 UTC
