### ISSUE TITLE
HA connection errors

### ISSUE THREAD

**Issue by lamboid** [peterbuga/HASS-sonoff-ewelink#28] opened 2019-01-02 17:07 UTC
HA appears to keep dropping connection to sonoff and cannot control anything.
Tried a number of restarts and also the debug script (which completes ok)

Any ideas?

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 277, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sonoff.py", line 437, in turn_on
    self._state = self._hass.data[DOMAIN].switch(True, self._deviceid, self._outlet)
  File "/config/custom_components/sonoff.py", line 341, in switch
    self._ws.send(json.dumps(payload))
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 239, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 264, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 425, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 109, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

**Comment by peterbuga** [comment] 2019-01-02 18:05
This is a really weird one :/ are you behind some firewall? the debug script connects to a different server than the websocket (which executes the on/off actions).

try using the files from `websocket` branch, they'll soon be merged into main one. if you still encounter this problem most likely there's a connectivity problem on your side. nonetheless keep posting the error logs and we'll figure it out ;)

**Comment by lamboid** [comment] 2019-01-02 23:10
updated the py scripts and initially pulling down the status ok but appears to fail pretty quick :(

`websocket error: Connection is already closed.`

**Comment by peterbuga** [comment] 2019-01-03 08:16
let's take this 1 by 1, i'm not blaming you but this definitely looks like local problem:
1. does eWeLink app works properly? is it on the same network with the HA install? 
2. what type of HA installation do you have?
3. as stated above, do you have any kind of firewall? 
4. what version of python `wesbsockets` do you have installed ? (depends on your type of HA installation, a possible quick fix would be to manually remove it - google details for this action - and the component will reinstall it automatically)

in theory the sonoff devices are using the same websocket-type of communication, therefore if everything is on the same network you should definitely be able to connect from HA.
another quick debug idea would be to spin up a test virtual machine, do a quick fresh install of HA and activate this plugin, if it works then there's definitely something wrong on your current install.

**Comment by lamboid** [comment] 2019-01-03 09:23
I think I might have found my issue or at least an influence!

I have a NodeRed flow running every minute and noticed it was firing a turn_x request on every execution rather than if request <> state.

Therefore I was firing turn_on/off commands to three switches every minute. I assume this overlap might have been a cause.

Edited the flow to only execute commands if current status does not match the desired status and not seen any errors in a couple of hours so far.

If things go wrong again, I will walk through the suggestions given previously.

**Comment by peterbuga** [comment] 2019-01-03 10:44
> How do I check websockets version?

i've never played with a hassio install (i have virtual env one) but in theory you should be able to run this and get the info (if i'm wrong just google a bit how to find it in a hassio install, can't be that hard)
`pip3 show websockets`

**Comment by lamboid** [comment] 2019-01-03 20:49
> > How do I check websockets version?
> 
> i've never played with a hassio install (i have virtual env one) but in theory you should be able to run this and get the info (if i'm wrong just google a bit how to find it in a hassio install, can't be that hard)
> `pip3 show websockets`

bash-4.4# pip3 show websockets
Name: websockets
Version: 6.0

 :)

**Comment by WantedLange** [comment] 2019-01-04 15:14
I get the same kind of errors.

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sonoff.py", line 437, in turn_on
    self._state = self._hass.data[DOMAIN].switch(True, self._deviceid, self._outlet)
  File "/config/custom_components/sonoff.py", line 341, in switch
    self._ws.send(json.dumps(payload))
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 239, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 264, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 425, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 109, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

This have worked, but might became unstable after installing Node-Red

**Comment by peterbuga** [comment] 2019-01-04 22:52
for now i will assume it's a configuration problem on your side and close this issue. feel free to re-open it if you can provide more details on how to reproduce the problem.

**Closed by peterbuga** 2019-01-04 22:52 UTC

**Comment by eugeneniemand** [comment] 2019-02-07 08:48
@peterbuga I get the same problem as above, they will work for days then it just starts failing. I'm using HASS Docker image. I've not thought of trying the mobile app yet to rule out a sonoff server issue. I will try when I'm home

**Comment by peterbuga** [comment] 2019-02-07 10:31
@eugeneniemand are you 100% sure you don't have any internet connectivity issues?

**Comment by WantedLange** [comment] 2019-02-07 10:58
I also have this problem still 

Every time i include an entity in node red, the component will crash/not respons after some hours

**Comment by eugeneniemand** [comment] 2019-02-07 15:58
@peterbuga hi 100% I'm at the office and connecting via SSH and Lovelace so its definitely got internet. Yesterday I restarted HASS and that resolved it but I tried restarting now and it has not fixed the issue. I'm one 0.86.0b0 if that makes any difference

**Comment by eugeneniemand** [comment] 2019-02-07 19:21
@peterbuga just got home and tried HASS and get above error. Tried eWeLink app and it had right status and it worked first time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peterbuga** [comment] 2019-02-08 13:36
@eugeneniemand I cannot keep compatibility and/or test a lost of HA installs/setups. i'm thinking that node red is querying the component much faster than it should or somehow it messes with the websocket part (which is crucial part for this component to work!).

until someone can provide a flow that i can replicate the error i will keep this issue closed. 
in the same time i urge any of you having this problems to test it the component (with a test HA install or something similar) first without node red and if everything seems stable for a while add node red to the whole setup.

**Comment by eugeneniemand** [comment] 2019-02-08 16:51
@peterbuga I don't use node red just vanilla HA. I would love to reproduce it but I'm not sure why this is happening. I wonder if there is an issue on eWeLink side as mine was working fine for 2 weeks and then in the last three days started playing up. Thanks for your help in any case

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WantedLange** [comment] 2019-02-18 19:40
Im not that hard of a coder.
Can I do anything to help you troubleshoot?
What can I provide for you

**Comment by peterbuga** [comment] 2019-02-19 08:29
@WantedLange unless someone can provide a way for me to duplicate & debug this problem there's not much for me i can do, must be some sort of combination of setup+firewall+overall-network that triggers this. i guess you have to go custom firmware way...
