### ISSUE TITLE
why cannot turn off  sonoff from automation?

### ISSUE THREAD

**Issue by violgore** [peterbuga/HASS-sonoff-ewelink#113] opened 2019-05-14 12:40 UTC
why cannot turn off  sonoff from automation?

I cant in the last update,
 I use 
switch.turn_off   , I try homeassistant.turn_off
but nothing 

Thanks

**Comment by neonwrx** [comment] 2019-05-19 07:08
such a problem, what can help?

**Comment by violgore** [comment] 2019-05-19 08:34
'1558179512434':
  alias: PORTERILLO
  sequence:
  - data:
      entity_id: switch.sonoff_1000646fec
    service: switch.turn_on
  - delay: 00:00:01
  - data:
      entity_id: switch.sonoff_1000646fec
    service: switch.turn_off


This is a script, I calle from automation

- id: '1557254386808'
  alias: PORTERILLO ON
  trigger:
  - entity_id: switch.sonoff_1000646fec
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    service: script.1558179512434

When I switch on sonoff , not go to OFF

sorry for my english
Thanks in advanced

**Comment by hdjweb** [comment] 2019-06-02 02:08
I have the same problem with outgoing home automation to turn off all lights

**Comment by peterbuga** [comment] 2019-07-01 20:10
pretty much duplicate of https://github.com/peterbuga/HASS-sonoff-ewelink/issues/92

TLDR; ewelink doesn't support toggle of multiple devices in the same time (or very fast), add a 1-2sec (or increase the value) delay between different switches

@violgore in your case you could use the inching option available in the latest firmwares

**Closed** 2019-10-08 17:34 UTC
Labels: duplicate
