### ISSUE TITLE
API for region "as" is down (as-disp.coolkit.cc)

### ISSUE THREAD

**Issue by difelice** [peterbuga/HASS-sonoff-ewelink#169] opened 2019-10-19 14:29 UTC
Not reachable at least from my location and there others:
https://check-host.net/check-ping?host=as-disp.coolkit.cc

HA log:
```python
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 167, in _async_setup_component
    hass, processed_config
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 53, in async_setup
    hass.data[DOMAIN] = Sonoff(hass, config)
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 100, in __init__
    self.do_login()
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 213, in do_login
    self.set_wshost()
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 221, in set_wshost
    r = requests.post('https://%s-disp.coolkit.cc:8080/dispatch/app' % self._api_region, headers=self._headers)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='as-disp.coolkit.cc', port=8080): Max retries exceeded with url: /dispatch/app (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x68bc3550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

### Update
The IOS app is showing "failed" on every service check:
<img src="https://user-images.githubusercontent.com/3169762/67159425-2c4d5980-f30a-11e9-89b1-1f14c020a557.jpeg" width="300" />

## LAN Mode?
I'm able to use devices via LAN though. @peterbuga have you explore the possibility of using LAN mode to get state and interact with devices?

This is an example request to turn switch OFF:
```
POST http://192.168.1.75:8081/zeroconf/switch
{
    "data": "xxxxx0xxxx0xxxxxxxxxxx0xxxx0xxx0xxxxx00xxxx=",
    "deviceid": "000000x000",
    "encrypt": true,
    "iv": "xxxxxxx0xxx0xxxxxxxxxx==",
    "selfApikey": "xxxx0x0x-xx0x-00xx-xx00-0000xxxx0000",
    "sequence": "1571492812598"
}
```

If this is somehow possible, we could refresh list of devices once a day, and the rest could be done via LAN (states and actions).

Just a thought.

Cheers.

**Comment by peterbuga** [comment] 2019-10-20 18:22
@difelice 1st of all i think the example request you posted is missing some information otherwise i can't quickly figure it out what's telling the sonoff to turn off.
despite that, you're one of the fine persons that are using the new sonoffs that support this DIY direct action on them, why don't you configure them like this in HA and skip altogether this custom component?

>If this is somehow possible, we could refresh list of devices once a day, and the rest could be done via LAN (states and actions).

unfortunately your proposal to deal with the problem you're experiencing is somehow flawed and requires huge code re-writes with not-so-much benefit IMO. i've been excited when sonoff-lan project came on but soon after i realized that the support for it it's a bit erratic on various devices, i hoped it'll be improved/fixed with further fw updates but itead team keeps disappointing over and over...

this is pretty much a duplicate of https://github.com/peterbuga/HASS-sonoff-ewelink/issues/50 so i'm going to close it for now

**Closed by peterbuga** 2019-10-20 18:22 UTC
Labels: duplicate
