### ISSUE TITLE
New eWeLink device Sonoff G1

### ISSUE THREAD

**Issue by dk253** [peterbuga/HASS-sonoff-ewelink#15] opened 2018-12-11 17:31 UTC
not sure where to put this:

```
[
  {
    "__v": 0, 
    "_id": "[hidden]" 
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "brandName": "New Smart ", 
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "deviceUrl": "", 
    "deviceid": "[hidden]" 
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "extra": {
      "_id": "[hidden]" 
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx", 
        "brandId": "5735f5f906d9751d4f109629", 
        "description": "20181023003", 
        "mac": "xx:xx:xx:xx:xx:xx", 
        "manufacturer": "\u90d1\u5dde\u5e02\u4e2d\u539f\u533a\u6c47\u8bda\u7535\u5b50\u6750\u6599\u7ecf\u8425\u90e8", 
        "model": "PSF-B01-GL", 
        "modelInfo": "589833ac2f979b623e2f503f", 
        "ui": "\u5355\u901a\u9053\u5f00\u5173", 
        "uiid": 6
      }
    }, 
    "group": "", 
    "groups": [], 
    "ip": "[hidden]" 
    "location": "", 
    "name": "[hidden]", 
    "online": true, 
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "params": {
      "fwVersion": "1.8.1", 
      "rssi": -57, 
      "staMac": "xx:xx:xx:xx:xx:xx", 
      "startup": "off", 
      "switch": "off"
    }, 
    "productModel": "G1", 
    "settings": {
      "alarmNotify": 1, 
      "opsHistory": 1, 
      "opsNotify": 0
    }, 
    "sharedTo": [], 
    "showBrand": true, 
    "type": "10", 
    "uiid": 6
  }
]
```

**Comment by dk253** [comment] 2018-12-11 17:32
Does that help?

**Comment by peterbuga** [comment] 2018-12-12 09:59
Hi :) thanks for sharing 
The way I see it your device it's a generic switch, you should just install/enable the component and the device will show up in your HA. 

Give it a try and let me know (with error logs) if there's something wrong.

**Comment by 2016for** [comment] 2018-12-16 15:55
@dk253 Do let us know if your device is working so that we can close this issue and add it in the rapidly expanding compatibility list.

Thanks.

**Comment by peterbuga** [comment] 2019-01-03 18:15
@dk253 could you please let me know if this device works with the component? 
if positive, i would appreciate if you could specify the used firmware version too, thanks!

**Comment by peterbuga** [comment] 2019-01-08 13:15
i'm closing this due to no reply back 😞. 
i have high assumptions this actually works ok because if follows the same pattern as many other devices.

**Closed by peterbuga** 2019-01-08 13:15 UTC

**Comment by stavfx** [comment] 2019-06-27 02:13
I think the device I have is the same one as this.
https://www.amazon.com/gp/product/B07K9P9JYN/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

It shows up in the eWeLink app as 
ManufacturerL New Smart
Model: G1
Firmware: PSF-B01-GL

I can confirm it works perfectly, including very fast response time from the door sensor.
