### ISSUE TITLE
Sonoff S26 pn 2.6.1

### ISSUE THREAD

**Issue by Yoavcwix** [peterbuga/HASS-sonoff-ewelink#47] opened 2019-01-26 21:47 UTC
This is an amazing and much needed project, so firstly thanks for putting this together! Just tested my S26s which are on firmware 2.61 (I could not choose to update to 2.6 fro 1.8), so far no recognition in HA. Checked logs, all seems fine with authentification.
Anything else to check or any expected  expansion on the firmware that will be supported for this device?

TIA!

**Comment by peterbuga** [comment] 2019-01-27 12:06
hi @Yoavcwix 
just because the firmware is not explicitly marked as `yes` doesn't mean it's not working, it just mean that version has been confirmed to work for sure (i update the list from time to time). 
FW 2.6.1 should definitely work with no problem, so far I'm not sure what might go wrong on your side, in theory the switch entities should show up automatically, have you tried looking for them in the device list ?

meanwhile, try to run this too https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug and attach the output + mention HA version and install type. should give me a better view of what is happening on your side ;)

**Comment by Yoavcwix** [comment] 2019-01-27 21:55
Thanks Peter. Here is the output from the script.
HA: Hassio v. 0.86.3 on Raspberry Pi

```
[
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO18418",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSA-B01-GL",
        "modelInfo": "5aca25ef85a15a8f032672f7",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "controlType": "7",
      "fwVersion": "2.6.1",
      "init": 1,
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -71,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "off",
      "switch": "off",
      "timers": [
        {
          "at": "xxxx-xx-xxxxx:xx:xx.xxx",
          "coolkit_timer_type": "delay",
          "do": {
            "switch": "off"
          },
          "enabled": 1,
          "mId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
          "period": "30",
          "type": "once"
        }
      ]
    },
    "productModel": "S26",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "disable_timers": [
        {
          "at": "xxxx-xx-xxxxx:xx:xx.xxx",
          "coolkit_timer_type": "delay",
          "do": {
            "switch": "off"
          },
          "enabled": 1,
          "mId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
          "period": "30",
          "type": "once"
        }
      ]
    },
    "type": "10",
    "uiid": 1
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO18418",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSA-B01-GL",
        "modelInfo": "5aca25ef85a15a8f032672f7",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "controlType": "7",
      "fwVersion": "2.6.1",
      "init": 1,
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -69,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "off",
      "switch": "off",
      "timers": [
        {
          "at": "xxxx-xx-xxxxx:xx:xx.xxx",
          "coolkit_timer_type": "once",
          "do": {
            "switch": "on"
          },
          "enabled": 1,
          "mId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
          "type": "once"
        },
        {
          "at": "xxxx-xx-xxxxx:xx:xx.xxx",
          "coolkit_timer_type": "once",
          "do": {
            "switch": "off"
          },
          "enabled": 1,
          "mId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
          "type": "once"
        }
      ]
    },
    "productModel": "S26",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 1
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO18418",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSA-B01-GL",
        "modelInfo": "5aca25ef85a15a8f032672f7",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "controlType": "7",
      "fwVersion": "2.6.1",
      "init": 1,
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -64,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "off",
      "switch": "off",
      "timers": []
    },
    "productModel": "S26",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 1
  }
]
```

**Comment by peterbuga** [comment] 2019-01-28 13:21
I have to say, the above output has nothing out of ordinary and should totally show up in your HA.

If you have any kind of custom dashboard that *maybe* might block the auto-showing of new devices try to look closely in the entities list, try to do a search with "1000", all the sonoff devices start with this number, therefore you should have something like **switch.1000xxxx** or **switch.sonoff_1000xxxx** depending on the used branch.

**Comment by Yoavcwix** [comment] 2019-01-29 09:18
I have used Tileboard. Removed that, nothing new. Wondering if...
1. eWelink perhaps is blocking something?
2. If any custom components might be interfering? I have one other one at the moment.

What other logs could be useful to check?

**Comment by peterbuga** [comment] 2019-01-29 09:22
Did you actually searched the entities like I mentioned above? otherwise there must be some error logs or anything else, cannot help otherwise!

the eWeLink is not blocking anything because the output from above is the same one used in the component, if one works the other one should too ;) (long shot but i think it might be some configuration problem on your side ¯\_(ツ)_/¯)

**Comment by Yoavcwix** [comment] 2019-01-29 12:04
Yip, searched everything. Ill dive deeper into it and see what I can come up with when I can.

**Comment by Yoavcwix** [comment] 2019-01-29 22:03
SOLVED: Changed region to 'as' from 'eu' and sonoffs appear in entities :)

**Comment by peterbuga** [comment] 2019-01-29 22:12
That's a bit odd, the region should've change automatically even if you selected the wrong one (to mention that the sonoff-debug.py uses the same logic, so it should've totally worked in the first place, unless you ran the script from a different device or your HA is behind some kind of firewall :| )

Can you please tell me if your username is an email or phone number (and if so what number format/country?)
Also can you do a small test too: please go to eWeLink app, logout, at login screen select a country from Europe and try to login normally (be sure to be on the same network like HA device). please let me know if you get an error/message or it just logins normally.

**Comment by peterbuga** [comment] 2019-04-08 09:26
@Yoavcwix any updates regarding this?

**Closed** 2019-04-09 12:42 UTC
